{
 "title": "Iot service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество генераций пакетов в data-simulator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "generated_data_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество принятых запросов iot-controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "iot_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Обработка однократных правил",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "single_rule_success_total", "legendFormat": "Успешные проверки правила" },
    { "expr": "single_rule_fail_total", "legendFormat": "Неуспешные проверки правила" }
   ]
  },
  {
   "title": "Обработка многократных правил",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "multiple_rule_success_total", "legendFormat": "Количество успешных обработок" },
    {
     "expr": "multiple_rule_fail_total",
     "legendFormat": "Количество неуспешных обработок"
    }
   ]
  }
 ]
}